### ISSUE TITLE
Bug - Sallen Key - abs() take always the long version

### ISSUE THREAD

**Issue by DerozerDSP** [janne808/kocmoc-rack-modules#10]
According to [this](https://stackoverflow.com/a/6215567/365251) (and tested on your code):

_The practice is different and C++ 0X aligned the theory with the practice. <math.h> gives you the symbols defined in the global namespace and perhaps also in the std namespace while using <cmath> gives you the symbols defined in the std namespace and **perhaps** also in the global namespace._

 in fact your [abs()](https://github.com/janne808/kocmoc-rack-modules/blob/master/src/sallenkey.cpp#L294) will always use the int/long version on <stdlib.h> instead of the floating point in cmath, even if you include it: `if (abs(x_k2 - x_k) < 1.0e-9)` 

I suggest you to fix it using `std::abs` instead (I mean: it seems your intention is to evaluate the double version due to 1.0e-9, not the integer one).

Can you fix it?

**Comment by janne808** [comment]
This is not correct, C++ can overload functions based on the context of variable types and this is what happens on GCC.

Please see https://godbolt.org/z/MnrG1nTna

It seems fabs() provides the best optimization, you don't want standard library function calls in a tight DSP inner loop.

**Comment by DerozerDSP** [comment]
It "depends", its not guaranteed. In fact, if I compile your code (mingw) using std::abs() instead of abs(), the results are different.
Here's two same module, both with abs() and keeping your code as is:

<img width="195" alt="image" src="https://github.com/janne808/kocmoc-rack-modules/assets/130961671/63128731-23ca-4dc3-9987-ded232a5c45a">

Here's the comparison using in one your code, in one force abs(int) (again, identical, so your code use the int version):

<img width="195" alt="image" src="https://github.com/janne808/kocmoc-rack-modules/assets/130961671/63128731-23ca-4dc3-9987-ded232a5c45a">

Here's the comparison using in one your code, in the other std::abs:

<img width="196" alt="image" src="https://github.com/janne808/kocmoc-rack-modules/assets/130961671/69516dd4-91e0-4c88-93d9-72d346b987dd">

As said in the post, "perhaps" compiler will take the abs in the std namespace instead of global (where abs live, within stdlib.h).

I think you could quickly check this yourself compiling your code with different abs() function...
