### ISSUE TITLE
Sallen Key - HP

### ISSUE THREAD

**Issue by DerozerDSP** [janne808/kocmoc-rack-modules#11]
Hi there,

is there possible to calculate HP output from SKF/Sallen Key filter?
Can you give to me some hits to optain it correctly?

Thanks

**Comment by DerozerDSP** [comment]
@janne808 : any tips about it? Thanks

**Comment by janne808** [comment]
This is not the right forum for questions like this but I can say that there is no easy way to get highpass output out of the code without deriving the full trapezoidal difference equation with pen and paper.
