### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SteveRussell33** [janne808/kocmoc-rack-modules#12]
Should be ``(float)`` here right? https://github.com/janne808/kocmoc-rack-modules/blob/00a0e123b0e0838112262cd5417cad75f52ce887/src/LADR.cpp#L123-L124

**Comment by janne808** [comment]
Oops, that's right. Thanks for pointing it out.

Fixed in:
https://github.com/janne808/kocmoc-rack-modules/commit/634b517cc45cdc8efff0d6cf616551d0e8eb7047
