### ISSUE TITLE
SVF-1 no longer with us :(

### ISSUE THREAD

**Issue by Petervos2018** [janne808/kocmoc-rack-modules#2]
After updating to 1.2.5 we get this : 

 "plugin": "kocmoc",
      "version": "1.2.1",
      "model": "SVF-1",
![KocMocBug](https://user-images.githubusercontent.com/46076474/75877300-aa248400-5e17-11ea-96dd-9c1ca34e2b91.png)

Did you rename it ? If so there will be NO backward compatibility with older patches.

Greetings Peter.

**Comment by janne808** [comment]
That's right, the module is now called "SVF". Sorry for the inconvenience.

**Comment by janne808** [comment]
The old patches should now work even with the new plugins.
