### ISSUE TITLE
filtah seems to run into rounding errors with lower sampling rates

### ISSUE THREAD

**Issue by hexdump0815** [janne808/kocmoc-rack-modules#3]
it looks like i discovered a similar problem with filtah as i some months ago discovered with pErCO from bidoo: if used with low sample rates like 22.05khz (which i'm sometimes using on the sonaremin to reduce the cpu usage - you have to set it in the vcvrack settings file as 22050 as its not available from the menu) then something simlar happens like described here in the old pErCO issue: https://github.com/sebastien-bouffier/Bidoo/issues/142 ... with filtah i saw it at 22.05khz and when the frequency knob goes to the end - then the module at some point gets lost and can not be brought back to normal operation anymore ... please let me know in case you cannot reproduce it, then i can try to make the description more detailed ... it would be nice if it could be made working also for such low sample rates - maybe the bidoo solution gives a hint about how to fix it?

best wishes and a lot of thanks in advance - hexdump

**Comment by janne808** [comment]
There's no module called Filtah in this repo, maybe you mean the Mockba Modular module?

**Comment by hexdump0815** [comment]
oh - sorry - i mixed them up because of the russian letters in them :)
