### ISSUE TITLE
DDLY nanV output

### ISSUE THREAD

**Issue by firolightfog** [janne808/kocmoc-rack-modules#5]
I ran into this with Rack 2.1.2 in Win:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/34127628/180595163-0486b0d1-2395-43c7-ae9b-6f032c5d20a9.png">

**Comment by firolightfog** [comment]
My solution to get over this was

- I added a second DDLY into my patch. 
- I connected the same inputs to the new DDLY. 
- Deleted the old DDLY.  

... all good now. I couldn't re-create the same issue ever since.

**Comment by firolightfog** [comment]
However it'd nicer to find the bug and fix the  module. ,:-T

**Comment by janne808** [comment]
New version 2.0.3 has had a fix for this for a while and will be imported to the VCV Rack library now. Thanks for the input, much appreciated.
