### ISSUE TITLE
Page selector in TRG not working

### ISSUE THREAD

**Issue by tobiza** [janne808/kocmoc-rack-modules#8]
It seems like the page selector in TRG is not working (anymore?).
Clicking on the small yellow box or the black area next to it doesn't change the page.
The other page can only be reached by following the active step.

Apart from that this is a great little trigger sequencer!

**Comment by janne808** [comment]
It only changes the page manually on click when "Follow active step" is inactive on the right mouse button module menu. 

Does this solve the issue with you?

**Comment by tobiza** [comment]
Yes. :) Thank you for the fast response! I wasn't aware of the connection between these two functions. Working great now!
